--UsersS--

CREATE INDEX IDX_UsersS_ROLE
ON UsersS(role_id);
GO

CREATE INDEX IDX_UsersS_NAME
ON UsersS(full_name);
GO


--CATEGORIES--

CREATE INDEX IDX_CATEGORY_NAME
ON CATEGORIES(category_name);
GO

--SUPPLIERS--

CREATE INDEX IDX_SUPPLIER_NAME
ON SUPPLIERS(company_name);
GO

--ProductS--

CREATE INDEX IDX_Product_CATEGORY
ON ProductS(category_id);
GO

CREATE INDEX IDX_Product_SUPPLIER
ON ProductS(supplier_id);
GO

CREATE INDEX IDX_Product_NAME
ON ProductS(Product_name);
GO

CREATE INDEX IDX_Product_STOCK
ON ProductS(stock);
GO

CREATE INDEX IDX_Product_STATUS
ON ProductS(status);
GO


--PURCHASES--

CREATE INDEX IDX_PURCHASE_DATE
ON PURCHASES(purchase_date DESC);
GO

CREATE INDEX IDX_PURCHASE_SUPPLIER
ON PURCHASES(supplier_id);
GO

CREATE INDEX IDX_PURCHASE_Users
ON PURCHASES(Users_id);
GO

CREATE INDEX IDX_PURCHASE_STATUS
ON PURCHASES(status);
GO


--PURCHASE DETAILS--

CREATE INDEX IDX_DETAIL_PURCHASE
ON PURCHASE_DETAILS(purchase_id);
GO

CREATE INDEX IDX_DETAIL_Product
ON PURCHASE_DETAILS(Product_id);
GO


--ÍNDICES COMPUESTOS--

CREATE INDEX IDX_Product_CATEGORY_STATUS
ON ProductS(category_id,status);
GO

CREATE INDEX IDX_PURCHASE_SUPPLIER_DATE
ON PURCHASES(supplier_id,purchase_date DESC);
GO

CREATE INDEX IDX_DETAIL_PURCHASE_Product
ON PURCHASE_DETAILS(purchase_id,Product_id);
GO
